name: Build & Push per Odoo version

on:
  push:
    branches: [main]
    paths:
      - "docker/**"
  workflow_dispatch:

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v4

      - id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            odoo14: 'docker/14.0/**'
            odoo17: 'docker/17.0/**'
      - name: Prepare matrix
        id: prepare
        run: |
          CHANGED=()
          for v in 14 17; do
            VAR="odoo${v}"
            echo "Checking $VAR =>"
            if [[ "${{ steps.filter.outputs[$VAR] }}" == "true" ]]; then
              CHANGED+=("{\"version\":\"${v}.0\"}")
            fi
          done
          JSON="{\"include\":[$(IFS=,; echo "${CHANGED[*]}")]}"
          echo "matrix=$JSON" >> $GITHUB_OUTPUT

  # build:
  #   needs: detect
  #   if: ${{ fromJson(needs.detect.outputs.matrix).include[0] != null }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix: ${{ fromJson(needs.detect.outputs.matrix) }}

  #   steps:
  #     - uses: actions/checkout@v4

  #     - uses: docker/setup-buildx-action@v3

  #     - uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USER }}
  #         password: ${{ secrets.DOCKERHUB_PASSW }}

  #     - name: Docker meta
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: borovlevas/odoo-base
  #         tags: |
  #           type=raw,value=${{ matrix.version }}
  #           type=raw,value=${{ matrix.version }}-${{ github.sha }}
  #           type=raw,value=${{ matrix.version }}-{{date 'YYYYMMDD'}}

  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: ./docker/${{ matrix.version }}
  #         file: ./docker/${{ matrix.version }}/Dockerfile
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
  #         cache-from: type=registry,ref=borovlevas/odoo-base:cache
  #         cache-to: type=registry,ref=borovlevas/odoo-base:cache,mode=max
